# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b40b591285ab1ac39ad1bca1854fad7e39a91f246cf5d797d2393aa239796c40bbeb645cccffd6e00ebca9e0964c59d3199b1e944ecfaf576423e5d0ff155a72

test:
  secret_key_base: 2ee66ea3546b5acf26a883a8a2b8676f8599759dc3f804592c8753288a5ed838d584f5e936d799b2d39111d158ca00760f44caf0ec4705214c1e94a284d82fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
